### ISSUE TITLE
Where is PenDecorator defined?

### ISSUE THREAD

**Issue by dgtlrift** [drepetto/chiplotle#2]
In some of the test code there are references to PenDecorator, but I cannot find where it is defined.

`
from chiplotle.hpgl.decorators.pen import PenDecorator
`

Where is this implemented?

**Comment by dgtlrift** [comment]
It seems that refactoring changes for 52323c7 and ffb8dbe resulted in changing PenDecorator to Pen but there doesn't seem to be reciprocal changes for ./chiplotle/geometry/core/label.py
./chiplotle/geometry/transforms/arrange_shapes_on_path.py
./chiplotle/tools/geometrytools/get_shape_intersections.py
I did try to change those references, but ran into an issue with 

```
jim@jim-VirtualBox:~/project/chiplotle/repo/chiplotle$ python chiplotle/tools/geometrytools/get_shape_intersections.py
Traceback (most recent call last):
  File "chiplotle/tools/geometrytools/get_shape_intersections.py", line 29, in <module>
    s1 = bezier_path([randint(0, 200) for  i in range(12)], 1, 14)
  File "/home/jim/.local/lib/python2.7/site-packages/chiplotle/geometry/shapes/bezier_path.py", line 25, in bezier_path
    points = CoordinateArray(points)
  File "/home/jim/.local/lib/python2.7/site-packages/chiplotle/geometry/core/coordinatearray.py", line 14, in __init__
    self._data = [Coordinate(*list(p)) for p in coords]
TypeError: 'int' object is not iterable
```
